terraform/environment/sbox/rbac/20-rbac.tf
[DTSPO-8020](https://tools.hmcts.net/jira/browse/DTSPO-8020)
re-added rbac for secops bastion
```
[ ] Yes
[ x] No
```
=> re-added rbac for secops bastion

azure-pipelines.yaml, pipeline-templates/terraform-execute-rbac.yaml, pipeline-templates/terraform-execute.yaml
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPO-9049
Change description
Enable publishPlanResults to add terraform plan to ADO pipeline
Add dependency on sbox to nonprod and dependency on nonprod to prod
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
=> DTSPO-9049 - Add publishPlanResults

terraform/environment/nonprod/10-locals.tf, terraform/environment/nonprod/20-bootstrap.tf
=> feat: expand nonprod vnet address space

terraform/environment/nonprod/10-locals.tf, terraform/environment/nonprod/20-bootstrap.tf, terraform/environment/prod/10-locals.tf, terraform/environment/prod/20-bootstrap.tf, terraform/environment/sbox/10-locals.tf, terraform/environment/sbox/20-bootstrap.tf
=> exapanded vnet address space

terraform/environment/prod/10-locals.tf
=> udpated range

terraform/environment/sbox/21-bastion.tf, terraform/modules/bastion/10-variables.tf, terraform/modules/bastion/22-vm-extentions.tf
=> testing run command

azure-pipelines.yaml, terraform/environment/sbox/21-bastion.tf, terraform/modules/bastion/10-variables.tf, terraform/modules/bastion/12-tags.tf, terraform/modules/bastion/20-networking.tf, terraform/modules/bastion/21-virtual-machine.tf, terraform/modules/bastion/22-vm-extentions.tf, terraform/modules/bastion/24-keyvault.tf, terraform/modules/bastion/25-datadisks.tf, terraform/modules/bootstrap/10-variables.tf, terraform/modules/bootstrap/12-tags.tf, terraform/modules/bootstrap/20-resource-group.tf, terraform/modules/bootstrap/21-networking.tf, terraform/modules/bootstrap/22-keyvault.tf
https://tools.hmcts.net/jira/browse/DTSPO-11882
```
[ ] Yes
[x] No
```
=> feat: added common tags module

terraform/environment/sbox/10-locals.tf
DTSPO-1235
Applying latest image (1.0.4) to bastion sbox to ensure psql uses latest version. OpenJDK version 17 also added as part of DTSPO-12396 request.
```
[ ] Yes
[ X] No
```
=> DTSPO-12351 - update psql to latest version

terraform/modules/bastion/22-vm-extentions.tf
DTSPO-12351
```
[ ] Yes
[ ] No
```
Fix to resolve tag issues for VM extensions due to Bastion sbox deploy failure
=> Fix to resolve tag issues for VM extensions

.gitignore, terraform/modules/bastion/12-tags.tf
Minor `tag` update to prevent expiration warning for the bastions and especially `sbox` vms. Setting date far into future as recommended.
```
[ ] Yes
[ ] No
```
=> No expiration for bastions

terraform/modules/bootstrap/12-tags.tf
Adding expiresAfter to resources created in bootstrap module
```
[ ] Yes
[x] No
```
=> Add expiresAfter to bootstrap

azure-pipelines.yaml, terraform/modules/bastion/10-variables.tf, terraform/modules/bastion/22-vm-extentions.tf
https://tools.hmcts.net/jira/browse/DTSPO-14774
Add variables to enable updated bootstrap module to configure the Windows agents
```
[ ] Yes
[X] No
```
=> DTSPO-14774-Agent-variables

terraform/environment/nonprod/rbac/20-rbac.tf, terraform/modules/rbac/10-variables.tf, terraform/modules/rbac/21-role-assignment.tf
N/A
Added workaround to unblock ITHC testers using the bastions for testing.
=> fix: added temporary work around to unblock ITHC testers

terraform/environment/sbox/21-bastion.tf
https://tools.hmcts.net/jira/browse/DTSPO-16484
Remove references to old activegates and point to new ones
=> DTSPO-16484 - Remove old activegates

terraform/modules/bastion/22-vm-extentions.tf
https://tools.hmcts.net/jira/browse/DTSPO-16664
updating splunk uf version
=> update splunk uf version

terraform/environment/nonprod/21-bastion.tf
https://tools.hmcts.net/jira/browse/DTSPO-16664
Update nonprod dynatrace server url to activegate
=> Update nonprod dynatrace server url

terraform/environment/prod/21-bastion.tf
https://tools.hmcts.net/jira/browse/DTSPO-16665
update prod and secops prod server
=> update dynatrace prod server

terraform/modules/bastion/22-vm-extentions.tf
https://tools.hmcts.net/jira/browse/DTSPO-17788
revert source back to original state after splunk uf update
=> revert source back to original state

terraform/modules/bastion/21-virtual-machine.tf
https://tools.hmcts.net/jira/browse/DTSPO-17752
Add AUM settings to enable the VMs to be scanned for missing updates
=> Add-AUM-scan-enabled

terraform/modules/bastion/22-vm-extentions.tf
- Reverting module source back to master after testing - https://github.com/hmcts/terraform-module-vm-bootstrap/pull/67
=> Change module source back to master

terraform/modules/bastion/00-provider.tf, terraform/modules/bastion/10-variables.tf, terraform/modules/bastion/11-local.tf, terraform/modules/bastion/22-vm-extentions.tf
https://tools.hmcts.net/jira/browse/DTSPO-18633
- Creating a provider config `dcr` with the subscription id of each environments data collection rules
- Passing the new provider to the bootstrap module
=> Pass dcr provider to bootstrap module

terraform/environment/nonprod/00-init.tf, terraform/environment/nonprod/rbac/00-init.tf, terraform/environment/prod/00-init.tf, terraform/environment/prod/rbac/00-init.tf, terraform/environment/sbox/00-init.tf, terraform/modules/bastion/22-vm-extentions.tf, terraform/modules/bootstrap/00-provider.tf, terraform/modules/rbac/00-provider.tf, terraform/modules/vnet_peering/00-provider.tf, terraform/modules/vpn_peering/00-provider.tf
https://tools.hmcts.net/jira/browse/DTSPO-18828
Updated feature branch back to master
=> DTSPO-18828 - moving feature branch back to master

terraform/environment/sbox/10-locals.tf, terraform/environment/sbox/21-bastion.tf, terraform/modules/bastion/10-variables.tf, terraform/modules/bastion/21-virtual-machine.tf
https://tools.hmcts.net/jira/browse/DTSPO-24017
- Updating `bastion-sbox` to use new ubuntu 24.04 image
=> Use new bastion image on sbox

terraform/environment/nonprod/10-locals.tf, terraform/environment/nonprod/21-bastion.tf, terraform/environment/prod/10-locals.tf, terraform/environment/prod/21-bastion.tf
https://tools.hmcts.net/jira/browse/DTSPO-24017
- Upgrade bastion-nonprod and bastion-prod to use Ubuntu 24.04 image
=> Upgrade bastion nonprod and prod

terraform/environment/prod/21-bastion.tf, terraform/environment/sbox/21-bastion.tf
https://tools.hmcts.net/jira/browse/DTSPO-24384
- Upgrade secops bastion sbox to Ubuntu 24.04
=> Upgrade bastion-secops-sbox to Ubuntu 24.04

terraform/environment/prod/21-bastion.tf
https://tools.hmcts.net/jira/browse/DTSPO-24384
- Upgrading to Ubuntu 24.04 image for secops prod bastion
- Sbox already done successfully
=> Upgrade secops prod bastion to Ubuntu 24.04
